<?php
$this->title ="My Albums";
$this->headTitle($this->title);
?>

<p><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add')); ?>">Add new album</a></p>
<table border="1" cellpadding="1" cellspacing="1">
    <tr>
        <th>Sr. No</th>
        <th>Title</th>
        <th>Artist</th>
        <th>Actions</th>
    </tr>
    <?php $i=1; ?>
    <?php  foreach($this->albums as $album) : ?>
    <tr>
        <td><?php echo $i; ?></td>
        <td><?php echo $this->escape($album->title); ?></td>
        <td><?php echo $this->escape($album->artist); ?></td>
        <td>
            <a href="<?php echo $this->url(array('controller' =>'index', 'action' =>'edit', 'id' =>$album->id)); ?>">Edit</a>
            <a href="<?php echo $this->url(array('controller' =>'index', 'action' =>'delete', 'id' =>$album->id)); ?>">Delete</a>

        </td>
    </tr>
        <?php $i++; ?>
    <?php endforeach; ?>
</table>
