<?php
$this->title = 'Delete User';
$this->headTitle($this->title);
?>
<p>Are you sure that you want to delete user : '<?php echo $this->escape($this->user['fname'])." ".$this->escape($this->user['lname']) ?>'?</p>


<form action="<?php echo $this->url(array('action' => 'userdelete')); ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo $this->user['id']; ?>" />
		<input type="submit" class="btn btn-primary" name="del" value="Yes">
		<input type="submit" class="btn btn-primary" name="del" value="No">
	</div>

</form>
