<?php
$this->title = 'Delete Book';
$this->headTitle($this->title);
?>
<p>Are you sure that you want to delete '<?php echo $this->escape($this->book['name']) ?>' by
	'<?php echo $this->escape($this->book['author']) ?>'?</p>


<form action="<?php echo $this->url(array('action' => 'delete')); ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo $this->book['id']; ?>" />
		<input type="submit" class="btn btn-primary" name="del" value="Yes">
		<input type="submit" class="btn btn-primary" name="del" value="No">
	</div>

</form>
