<?php

/**
 * Model_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_User extends Model_Base_User
{
    public function listuser(){
        $users= '';
        $q = Doctrine_Query::create()
            ->from('Model_User');
        //echo $q->getSqlQuery(); exit;
        $users = $q->execute();
        return $users;
    }

    public function adduser($form)
    {

    }

    public function updateuser($form,$id){
        $fname = $form->getValue('fname');
        $lname = $form->getValue('lname');
        $email = $form->getValue('email');
        $password = $form->getValue('password');
        if(!empty($password)) {
            $q = Doctrine_Query::create()
                ->update('Model_User')
                ->set(array('fname'=> $fname,'lname'=> $lname,'email'=>$email,'password'=> $password))
                ->where('id='.$id);

        } else {
            $q = Doctrine_Query::create()
                ->update('Model_User')
                ->set(array('fname'=> $fname,'lname'=> $lname,'email'=>$email))
                ->where('id='.$id);
        }
        //$user->save();
        $save = $q->execute();
        return $save;
    }

    public function deleteuser($id)
    {
        $user = Doctrine_Core::getTable('Model_User')->findOneById($id);
        //$user->delete();
        $q = Doctrine_Query::create()
            ->delete('Model_User')
            ->where('id='.$id);
        $del = $q->execute();
        if(!empty($user->UserSettings)) {
            $user->UserSettings->delete();
            $q1 = Doctrine_Query::create()
                ->delete('Model_UserSettings')
                ->where('user_id='.$id);
            $del1 = $q1->execute();
        }

        return $del;

    }

}